services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  fastapi:
    ports:
      - 8000:8000
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0"
