services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: db
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  fastapi:
    ports:
      - 8000:8000
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0"
    depends_on:
      - db

volumes:
  postgres_data: